send SYNC, STOP command before suspending the port
Also add support for mounting check.

diff --git a/suspend-usb-device b/suspend-usb-device
--- a/suspend-usb-device
+++ b/suspend-usb-device
@@ -26,6 +26,11 @@ usage()
     cat<<EOF
 suspend-usb-device  Copyright (C) 2009  Yan Li <elliot.li.tech@gmail.com>
 
+This program sends a SYNCHRONIZE CACHE command followed by a
+START-STOP command (if the device supports it), and then suspends the
+USB port. At this point you can remove / disconnect your USB device
+safely.
+
 usage:
 $0 dev
 
@@ -46,12 +51,26 @@ if [ -z $1 ]; then
     exit 2
 fi
 
+set -u
+DEV_NAME=$1
+
+# umount it first
+if mount | grep "^$DEV_NAME "; then
+    echo
+    echo "detected above partition is still mounted, can't suspend device"
+    echo "umount them first"
+    exit 1
+fi
+
 # looking for the parent device with name like
 # /devices/pci0000:00/0000:00:1d.7/usb5/5-8
 
-DEVICE=$(udevinfo --query=path --name=$1 --attribute-walk | \
+DEVICE=$(udevinfo --query=path --name=${DEV_NAME} --attribute-walk | \
     egrep "parent device.*usb[[:digit:]]+/[[:digit:]]+-[[:digit:]]+'" | \
     head -n 1 | cut -d"'" -f2)
+
+# the trailing basename of ${DEVICE} is USB_BUS_ID
+USB_BUS_ID=${DEVICE##*/}
 
 if [ -z $DEVICE ]; then
     if [ -z $DEVICE ]; then
@@ -61,4 +80,5 @@ if [ -z $DEVICE ]; then
     fi
 fi
 
+echo -n "${USB_BUS_ID}" > /sys/bus/usb/drivers/usb/unbind
 echo 'suspend' > /sys/$DEVICE/power/level
